import Link from 'next/link'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import SubscribeForm from '@/components/SubscribeForm'
import { companyServices } from '@/lib/company-services'
import { solutions, salesOffers, caseStudies, carePlans } from '@/lib/sales'

function ArrowIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>}

function ProductSystemVisual(){
 return <div className="maturity-visual" aria-label="Illustration of connected product delivery">
  <div className="maturity-window"><div className="maturity-window-top"><i/><i/><i/><span>ga.tech workspace</span></div><div className="maturity-window-body"><aside><img src="/brand/ga-tech-logo.webp" alt=""/><span className="active">Overview</span><span>Product</span><span>Automation</span><span>Launch</span></aside><div className="maturity-dashboard"><div className="maturity-dashboard-head"><div><small>DIGITAL DELIVERY</small><h3>One owner. Connected outcomes.</h3></div><span className="demo-badge">SAMPLE UI</span></div><div className="maturity-module-grid">{[['Build','Product','01'],['Automate','AI/workflows','02'],['Create','Launch system','03'],['Scale','Cloud/backend','04']].map(([title,copy,num])=><div className="maturity-module" key={title}><span>{num}</span><strong>{title}</strong><small>{copy}</small></div>)}</div><div className="maturity-chart"><div><small>Clarify</small><b>Scope</b></div><span>→</span><div><small>Deliver</small><b>Launch</b></div><span>→</span><div><small>Extend</small><b>Care</b></div></div></div></div></div>
  <div className="maturity-float maturity-float-ai"><strong>Senior ownership</strong><span>Fewer handoffs</span></div><div className="maturity-float maturity-float-launch"><strong>Milestone delivery</strong><span>Visible progress</span></div><div className="maturity-float maturity-float-support"><strong>After launch</strong><span>Support & iteration</span></div>
 </div>
}

const realProof=caseStudies.filter(c=>c.kind==='Founder experience').slice(0,3)

export default function Home(){
 const structuredData={'@context':'https://schema.org','@type':'ProfessionalService',name:'ga.tech',url:'https://gauravanand.tech',logo:'https://gauravanand.tech/brand/ga-tech-logo.webp',areaServed:'Worldwide',description:'Founder-led digital product studio for startups and growing businesses.',serviceType:['Digital product development','AI automation','Design and content','Backend and cloud engineering']}
 return <><Nav/><main id="main-content">
  <section className="maturity-hero"><div className="site-shell maturity-hero-grid"><div className="maturity-hero-copy"><p className="company-kicker">FOR STARTUPS & GROWING TEAMS</p><h1>Launch products and automation faster—<em>without hiring three separate teams.</em></h1><p className="maturity-lead">Senior-engineering-led product, AI automation and launch delivery with one accountable owner from scope to launch.</p><div className="maturity-actions"><Link data-track="hero_request_scope" href="/contact" className="button button-primary button-lg">Request scope <ArrowIcon/></Link><Link data-track="hero_book_discovery" href="/book" className="button button-secondary button-lg">Book 20-min discovery</Link></div><div className="maturity-trust-row"><span><strong>Founder-led</strong><small>Direct delivery ownership</small></span><span><strong>7+ years</strong><small>Systems, cloud & applied AI</small></span><span><strong>1 business day</strong><small>Target enquiry response</small></span></div><p className="maturity-personality">Know exactly what you need? Request scope. Still deciding? Start with discovery.</p></div><ProductSystemVisual/></div></section>

  <section className="founder-proof-strip"><div className="site-shell founder-proof-strip-inner"><div><p className="company-kicker">WHY TRUST THE DELIVERY</p><strong>Founder experience spans production systems, large codebases, cloud/platform work and applied AI.</strong></div><p>The site distinguishes founder employment experience from ga.tech client work—no invented logos, testimonials or vanity metrics.</p><Link href="/case-studies">See proof →</Link></div></section>

  <section className="maturity-section maturity-soft"><div className="site-shell"><div className="maturity-section-head"><div><p className="company-kicker">CHOOSE YOUR SITUATION</p><h2>Different buyers need different sales paths.</h2></div><p>Start with the situation closest to yours instead of translating your problem into agency terminology.</p></div><div className="solution-grid">{solutions.map((s,i)=><article className="solution-card" key={s.slug}><span className="solution-index">0{i+1}</span><p className="company-kicker">{s.eyebrow}</p><h3>{s.title}</h3><p>{s.pain}</p><Link data-track="solution_click" data-track-label={s.slug} href={`/solutions/${s.slug}`}>See this path →</Link></article>)}</div></div></section>

  <section className="maturity-section"><div className="site-shell"><div className="maturity-section-head"><div><p className="company-kicker">WHAT GA.TECH DOES</p><h2>Four connected delivery capabilities.</h2></div><p>Product engineering is the core. AI, creative and cloud capabilities extend the outcome when the project needs them.</p></div><div className="solution-grid">{companyServices.map((s,i)=><article className="solution-card" key={s.slug}><span className="solution-index">0{i+1}</span><p className="company-kicker">{s.eyebrow}</p><h3>{s.title}</h3><p>{s.summary}</p><div className="solution-tags">{s.idealFor.slice(0,3).map(x=><span key={x}>{x}</span>)}</div><Link data-track="service_click" data-track-label={s.slug} href={`/services/${s.slug}`}>Explore →</Link></article>)}</div></div></section>

  <section className="maturity-section maturity-soft"><div className="site-shell"><div className="maturity-section-head"><div><p className="company-kicker">COMMERCIAL STARTING POINTS</p><h2>Know the likely size before you fill a form.</h2></div><p>Planning ranges are directional—not fixed quotes. If you have a fixed launch date, start scoping early: common engagements run roughly 1–14 weeks depending on complexity.</p></div><div className="starter-offer-grid">{salesOffers.map(o=><article className="starter-offer-card" key={o.key}><span>{o.label}</span><h3>{o.title}</h3><p>{o.copy}</p><small><b>Good for:</b> {o.goodFor}</small><div className="offer-commercials"><strong>{o.timeline}</strong><span>{o.planningRange}</span></div><Link data-track="offer_scope_click" data-track-label={o.key} href={`/contact?request=${encodeURIComponent(o.request)}`}>Scope this →</Link></article>)}</div></div></section>

  <section className="launch-window-strip"><div className="site-shell launch-window-grid"><div><p className="company-kicker">PLANNING A LAUNCH?</p><h2>Start scope before the deadline becomes the architecture.</h2></div><div className="launch-window-items"><span><strong>2–5 weeks</strong><small>Focused website / launch work</small></span><span><strong>2–6 weeks</strong><small>AI / workflow sprint</small></span><span><strong>6–14 weeks</strong><small>MVP / product build</small></span></div><Link data-track="launch_window_cta" href="/contact">Plan a launch →</Link></div></section>

  <section className="maturity-section"><div className="site-shell proof-section-grid"><div className="proof-intro"><p className="company-kicker">PROOF</p><h2>Translate technical depth into business confidence.</h2><p>These are real founder-experience examples. They are not presented as ga.tech client engagements.</p><Link href="/case-studies" className="company-text-link">View proof library →</Link></div><div className="proof-card-grid">{realProof.map(c=><article key={c.slug}><span>{c.kind.toUpperCase()}</span><h3>{c.title}</h3><p>{c.outcome}</p></article>)}</div></div></section>

  <section className="maturity-section maturity-dark"><div className="site-shell"><div className="maturity-section-head dark-head"><div><p className="company-kicker">WHY THIS MODEL</p><h2>Choose the operating model, not just the vendor category.</h2></div><p>ga.tech is designed for buyers who want senior ownership without building a full internal team for every project.</p></div><div className="comparison-table"><div className="comparison-row heading"><span>Option</span><span>Common trade-off</span><span>ga.tech response</span></div>{[['Multiple freelancers','Coordination and accountability split across people','One accountable delivery owner'],['Large agency','More layers between buyer and delivery','Founder-led execution close to the work'],['Internal hire','Slow and expensive for time-bounded project needs','Flexible fixed, milestone or care-plan engagement'],['AI/no-code alone','Fast prototypes can stall on integration and ownership','Engineering + automation + launch path']].map(r=><div className="comparison-row" key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><span>{r[2]}</span></div>)}</div></div></section>

  <section className="maturity-section"><div className="site-shell"><div className="maturity-section-head"><div><p className="company-kicker">RISK CONTROLS</p><h2>Reduce the fears that slow a buying decision.</h2></div><Link href="/working-with-us" className="company-text-link">Procurement, IP & commercial FAQ →</Link></div><div className="risk-grid">{['Written scope before build','Milestone demos for larger projects','No silent scope changes','Acceptance criteria upfront','Handover defined in writing','Stop/go checkpoints between major phases'].map((x,i)=><article key={x}><span>0{i+1}</span><strong>{x}</strong></article>)}</div></div></section>

  <section className="maturity-section maturity-soft"><div className="site-shell"><div className="maturity-section-head"><div><p className="company-kicker">AFTER LAUNCH</p><h2>Turn project work into ongoing operating support.</h2></div><p>Recurring support is optional and scoped separately, so buyers do not get trapped in a long contract just to launch.</p></div><div className="care-grid">{carePlans.map(p=><article key={p.title}><h3>{p.title}</h3><p>{p.fit}</p><ul>{p.includes.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></div></section>

  <section className="maturity-section"><div className="site-shell resource-nurture-row"><div><p className="company-kicker">NOT READY TO BUY?</p><h2>Take something useful with you.</h2><p>Use the free brief template or get occasional Build Notes. That gives the site a nurture path instead of losing every not-yet-ready visitor.</p><div className="maturity-actions"><Link href="/resources" className="button button-secondary">Free resources →</Link></div></div><div><p className="company-kicker">BUILD NOTES</p><SubscribeForm source="homepage"/></div></div></section>

  <section className="maturity-cta"><div className="site-shell maturity-cta-inner"><div><p className="company-kicker">CHOOSE YOUR NEXT STEP</p><h2>Know the project? Request scope. Need help deciding? Book discovery.</h2></div><div><p><strong>Target response:</strong> within 1 business day.</p><p>No obligation. No polished brief required.</p><div className="maturity-actions"><Link data-track="footer_request_scope" href="/contact" className="button button-primary button-lg">Request scope <ArrowIcon/></Link><Link data-track="footer_book_discovery" href="/book" className="button button-secondary button-lg">Book discovery</Link></div></div></div></section>
 </main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/></>
}
